### ISSUE TITLE
Increasing the framelength of LengthFieldBasedFrameDecoder in netty library

### ISSUE THREAD

**Issue by bensbox** [krux/tcp-stream-kafka-producer#11]
Hi again!

This is probably somewhat special, but i am getting the "TooLongFrameException" exception from the netty lib about 2-3 times a minute, while writing to the tcp-stream-producer.

> 2016-06-10T13:11:31.182 |ERROR [nioEventLoopGroup-23-2] c.k.b.l.BeaconListenerHandler - Error during message handling
io.netty.handler.codec.TooLongFrameException: frame length (19812) exceeds the allowed maximum (16384)
        at io.netty.handler.codec.LineBasedFrameDecoder.fail(LineBasedFrameDecoder.java:146) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.handler.codec.LineBasedFrameDecoder.fail(LineBasedFrameDecoder.java:142) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.handler.codec.LineBasedFrameDecoder.decode(LineBasedFrameDecoder.java:99) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.handler.codec.DelimiterBasedFrameDecoder.decode(DelimiterBasedFrameDecoder.java:232) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.handler.codec.DelimiterBasedFrameDecoder.decode(DelimiterBasedFrameDecoder.java:216) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [krux-tcp-stream-kafka-producer-1.3.2-full.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

The "problem" is the maxsize of 16384. I doubt it has anything to do with the payload itself.
I am currently running the stream-server with 15 "--port.topic" mappings, which is being written to with plain tcp-sockets of a single webserver about 1.000+ times a minute.

Is it possible to increase the Framesize in code or by configuration?

Thx!

**Comment by prashuj** [comment]
Use option --krux.decoder.frame.size to frame size, default value it 16K

**Comment by bensbox** [comment]
That did it ..thx alot :) You should add that to the documentation. Are there more settings like this?

**Comment by prashuj** [comment]
All these options are available when you say --help

Thanks again for using the application

Sent from my iPhone

On Jun 13, 2016, at 2:21 AM, "Ben" <notifications@github.com<mailto:notifications@github.com>> wrote:


That did it ..thx alot :) You should add that to the documentation. Are there more settings like this?

**Comment by bensbox** [comment]
Ok, i didn't look there, because the Readme.md was extensive enough - it is missing in there btw.
Sure thing - thanks for developing it. I will look at it more intensive and give you guys feedback.

Thx again!
