### ISSUE TITLE
Is JSON The Only Supported Payload?

### ISSUE THREAD

**Issue by sghaskell** [krux/tcp-stream-kafka-producer#16]
I'm testing your producer and sending plaintext data broken by newline. I'm getting errors complaining that data cannot be parsed as JSON. It doesn't explicitly say in the docs that JSON is the expected payload. Is JSON the only supported input for a TCP listener?

`2017-04-03T20:04:31.383 |ERROR [nioEventLoopGroup-3-1] c.k.b.l.BeaconListenerHandler - Cannot parse message as JSON
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)): Expected space separating root-level values
 at [Source:  2017-04-04T00:04:30.559Z I ACCESS   [conn10] Successfully authenticated as principal __system on local; line: 1, column: 7]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1486) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:463) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._verifyRootSpace(ReaderBasedJsonParser.java:1236) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parsePosNumber(ReaderBasedJsonParser.java:886) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:680) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.fasterxml.jackson.jr.ob.JSON._initForReading(JSON.java) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.fasterxml.jackson.jr.ob.JSON.mapFrom(JSON.java) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.krux.beacon.listener.BeaconListenerHandler.channelRead0(BeaconListenerHandler.java:68) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.krux.beacon.listener.BeaconListenerHandler.channelRead0(BeaconListenerHandler.java:29) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]`

**Comment by sghaskell** [comment]
Even sending a very simple JSON payload results in an error:

`echo '{"foo":"bar"}' | ncat -C localhost 33033`

`2017-04-03T21:15:09.657 |ERROR [nioEventLoopGroup-3-4] c.k.b.l.BeaconListenerHandler - Error during message handling
java.lang.NoSuchMethodError: joptsimple.OptionSpec.options()Ljava/util/List;
	at com.krux.kafka.helpers.PropertiesUtils.createPropertiesFromOptionSpec(PropertiesUtils.java:24) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.krux.kafka.producer.KafkaProducer.<init>(KafkaProducer.java:69) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.krux.beacon.listener.BeaconListenerHandler.channelRead0(BeaconListenerHandler.java:92) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at com.krux.beacon.listener.BeaconListenerHandler.channelRead0(BeaconListenerHandler.java:29) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [krux-tcp-stream-kafka-producer-1.3.0-full.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]`

Any guidance on how to format events would be helpful.

**Comment by sghaskell** [comment]
I'm not sure exactly what caused this error, but it had to do with `joptsimple.OptionSpec` in `com.krux.kafka.helpers.PropertiesUtils.java`. I unpacked the jar file, re-built the class from source to add some debugging and then re-packaged the jar and everything works now. I'm using Java JRE 1.8.0_121.

**Comment by sghaskell** [comment]
I modified this block of code in `com.krux.beacon.listener.BeaconListenerHandler` to handle the exception thrown by Jackson and suppress the stack trace for any payload that isn't JSON.

`    try
    {
      request = request.replace("\\x", "\\u00");
      request = request.replace("\\v", "\\u0013");

      try
      {
          JSON.std.mapFrom(request);
      } catch (Exception e) {
          LOG.debug("Request is not formatted as JSON -- Skipping JSON cleanup");
      }
    } catch (Exception e) {
      LOG.error("Cannot parse message as JSON", new String(request), e);
      long time = System.currentTimeMillis() - start;
      String mainTopic = (String)_topics.get(0);
      KruxStdLib.STATSD.time("errors.json_parse." + mainTopic, time);
    }
`
